### PR TITLE
Read only properties

### PR DESCRIPTION
**Pull request by rjb1000**
For some reason, this PR doesn't correctly show my delta versus the baseline V17.6.0 that I have checked in to the "TS26.512v17.6.0" branch of 5G-MAG/rt-common-shared.

### CODE REVIEW

**Comment by rjb1000** [comment]
Here is the delta I was hoping to see:
https://github.com/rjb1000/rt-common-shared/commit/5d0f9095a3f259ba823953f3e5020a8911117bb9

**Comment by davidjwbbc** [comment]
Fixed up git branches and merged

**Review by davidjwbbc — COMMENTED** [review]
Cherry-picked delta onto branch and merged

**Comment by rjb1000** [comment]
Thanks, @davidjwbbc. You'll need to explain what I did wrong to me next time we talk!

**Pull request closed without merging**
