### PR TITLE
Fix M3 interface definitions

### PR DESCRIPTION
**Pull request by davidjwbbc**
Addresses issues raised in 5G-MAG/rt-common-shared#12.

Fix ContentHostingConfiguration purge request schema to remove extra field.
Fix Certificate identifier to be a single value.
Add 409 Conflict response to Certificates DELETE interface for when a certificate is still in use by a ContentHostingConfiguration.

### CODE REVIEW

**Comment by davidjwbbc** [comment]
> I notice you have added _409 Conflict_ as a potential error for the _destroyServerCertificate_ operation. Am I right in thinking that this would be returned if an attempt is made to destroy a certificate that is still referenced by a Content Hosting Configuration?

Yes, that's the intention.

**Comment by rjb1000** [comment]
@davidjwbbc: Please could you create a new Improvement issue in the 5G-MAG/Standards repository requesting the addition of _409 Conflict_ as an error for the _M1\_ServerCertificatesProvisioning\_destroyServerCertificate_ operation so that we can expose this error to the 5GMS Application Provider.

(I think that the issue likely affects all M1 subresources of the Provisioning Session resource, so a more comprehensive title and description is needed.)

(Maybe we could go even wider and overhaul the HTTP response code specifications for service-based operations in all M1 APIs.)

**Comment by rjb1000** [comment]
After reviewing the M1 domain model in TS 26.501 figure 5.3.1-1, @davidjwbbc and I concluded that the only possible conflicts today are in attempting to destroy a Server Certificate or Content Preparation Template that is still referenced by a Content Hosting Configuration. And so both _M1_ServerCertificatesProvisioning_destroyServerCertificate_ and M1_ContentPreparationTemplatesProvisioning_destroyContentPreparationTemplate_ need to be able to return _409 Conflict_. Please document this on a new issue, @davidjwbbc.

For all other subresources of the Provisioning Session, we assume that destroying the Provisioning Session also destroys all subresources. Please verify that this is clearly specified in TS 26.512, @davidjwbbc and raise a second issue if not.

**Comment by davidjwbbc** [comment]
> For all other subresources of the Provisioning Session, we assume that destroying the Provisioning Session also destroys all subresources. Please verify that this is clearly specified in TS 26.512, @davidjwbbc and raise a second issue if not.

This is already stated briefly in TS 26.512 Section 4.3.2.5, but probably ought to be reiterated in Section 7.2.2.

**Comment by rjb1000** [comment]
> This is already stated briefly in TS 26.512 Section 4.3.2.5, but probably ought to be reiterated in Section 7.2.2.

I think that both clauses could be improved. So please go ahead and raise a new Clarification issue to do this and we can work out the details there.

**Pull request merged**
